# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import dialog_table
from dialog_table import Ui_Dialog
from functools import partial

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 100, 231, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 200, 231, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 300, 231, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 400, 231, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setStyleSheet("background-image: url('28.jpg'); background-repeat: no-repeat; background-position: center;")
        MainWindow.setCentralWidget(self.centralwidget)
        self.pushButton.setStyleSheet("background: #0d6e79; font: bold large serif;")
        self.pushButton_2.setStyleSheet("background: #0d6e79; font: bold large serif;")
        self.pushButton_3.setStyleSheet("background: #0d6e79; font: bold large serif;")
        self.pushButton_4.setStyleSheet("background: #0d6e79; font: bold large serif;")
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Manager"))
        self.pushButton.setText(_translate("MainWindow", "Склады 🏭 🏚"))
        self.pushButton_2.setText(_translate("MainWindow", "Товары"))
        self.pushButton_3.setText(_translate("MainWindow", "Заказы 🛒🛍"))
        self.pushButton_4.setText(_translate("MainWindow", "Клиенты 👩‍💼🧑‍💼"))
        
        self.pushButton.clicked.connect(partial(self.table_dialog, "Склады"))
        self.pushButton_2.clicked.connect(partial(self.table_dialog, "Товары"))
        self.pushButton_3.clicked.connect(partial(self.table_dialog, "Заказы"))
        self.pushButton_4.clicked.connect(partial(self.table_dialog, "Клиенты"))
        
        

    def table_dialog(self, table_name):
        Dialog = QtWidgets.QDialog()
        ui_table = Ui_Dialog()
        with dialog_table.con:
            header = dialog_table.con.execute(f'PRAGMA table_info({table_name})').fetchall()
            column_names = [column[1] for column in header if column[1] != 'id']
            column = ', '.join(column_names)
            print(column)
            inf = dialog_table.con.execute(f'SELECT {column} FROM {table_name}').fetchall()
             
        ui_table.TABLE = [tuple(column_names)] + inf
        ui_table.table_name = table_name
        ui_table.column_names =  column_names 
        ui_table.setupUi(Dialog)
    
        Dialog.show()
        Dialog.exec_()





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    
    sys.exit(app.exec_())
